name: Whiskers Check
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: catppuccin/setup-whiskers@v1
        with:
          whiskers-version: 2.5.1
      - run: |
          whiskers templates/main.tera --output-format yaml --check --overrides "
          {
            \"topic\": \"NumPy Basics\",
            \"status\": \"Completed\",
            \"date\": \"2025-03-08\",
            \"notes\": \"Understood array operations and basic functions.\"
          }" -o learning_progress.yaml

