<<<<<<< HEAD
name: Learning Progress Tracker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  track-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Whiskers
        run: pip install whiskers

      - name: Render YAML from template
        run: |
          whiskers -t learning_progress.tera -o learning_progress.yaml
        env:
          TOPIC: "Python Basics"
          STATUS: "Completed"
          DATE: "$(date +'%Y-%m-%d')"
          NOTES: "Finished Python fundamentals."

      - name: Validate YAML file
        run: |
          python -c 'import yaml; yaml.safe_load(open("learning_progress.yaml"))'

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add learning_progress.yaml
          git commit -m "Update learning progress: ${{ env.TOPIC }}"
          git push origin master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "update-learning-progress"
          base: "master"
          title: "Update Learning Progress: ${{ env.TOPIC }}"
          body: "Automated PR for learning progress update."
          commit-message: "Update learning progress: ${{ env.TOPIC }}"
