name: AI Olympiad Progress Tracker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Commit and Push Changes
      run: |
        git checkout -b progress-update-$(date +%Y-%m-%d)
        echo "## Learning Update on $(date)" > progress_report.md
        git add progress_report.md
        git commit -m "Update learning progress on $(date)"
        git push --force https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/MahmudGalib7/AI-Olympiad.git progress-update-$(date +%Y-%m-%d)

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        head: progress-update-$(date +%Y-%m-%d)
        title: "Update Progress: $(date)"
        body: "This pull request contains updates on the learning progress made towards AI Olympiad."
