name: Progress Tracker

on:
  push:
    branches:
      - master

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install whisker
      - name: Install whisker
        run: |
          pip install --upgrade whisker  # Ensure we are getting the latest version

      # Verify whisker installation
      - name: Verify whisker installation
        run: |
          whisker --version  # This should work if whisker is installed correctly

      # Track progress with whisker
      - name: Track progress
        run: |
          whisker track  # Assuming this command works after successful installation
