name: Progress Tracker

on:
  push:
    branches:
      - master

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install whisker
      run: |
        pip install whisker

    - name: Verify whisker installation
      run: |
        whisker --version

    - name: Run whisker track
      run: |
        echo "Tracking progress..."
        whisker track
